"""
Django settings for geodjango_tutorial project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import socket

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

with open(f'{BASE_DIR}/secret_key.txt') as f:
    SECRET_KEY = f.read().strip()

# SECRET_KEY = 'django-insecure-e)1z$4h0315y92b@frxwv@=-*u7n6$bvo2u(z&^%+m#y2b)7rg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'world.apps.WorldConfig',
    'django.contrib.gis',
    'user_location',
    'crispy_forms',
    'crispy_bootstrap4',
    'leaflet',
]

CRISPY_FAIL_SILENTLY = not DEBUG
LEAFLET_CONFIG = {'DEFAULT_CENTER': (53.0, -8.0),
                  'DEFAULT_ZOOM': 6,
                  'MIN_ZOOM': 3,
                  'MAX_ZOOM': 18,
                  'RESET_VIEW': False,
                  'SCALE': None,
                  'OPACITY': 0.5,
                  }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'geodjango_tutorial.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geodjango_tutorial.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'gis',
        'USER': 'root',
        'PASSWORD': 'docker',
        'HOST': 'localhost',
        'PORT': '25432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'geodjango_tutorial/static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK = "bootstrap4"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

POSTGIS_PORT = os.environ.get('POSTGIS_PORT', '25432')
PROJECT_NAME = os.environ.get('PROJECT_NAME', 'geodjango_tutorial')
DEPLOY_SECURE = os.environ.get('DEPLOY_SECURE', 'False').lower() == 'true'
POSTGIS_USER = os.environ.get('POSTGIS_USER', 'root')
POSTGIS_NAME = os.environ.get('POSTGIS_NAME', 'gis')
POSTGIS_PASS = os.environ.get('POSTGIS_PASS', 'docker')
POSTGIS_HOST = os.environ.get('POSTGIS_HOST', 'localhost')


if (socket.gethostname() == "localhost") | (socket.gethostname() == "MacBook-Pro-2"):
    DATABASES["default"]["HOST"] = "localhost"
    DATABASES["default"]["PORT"] = POSTGIS_PORT
else:
    DATABASES["default"]["HOST"] = POSTGIS_HOST
    DATABASES["default"]["PORT"] = POSTGIS_PORT
    DATABASES["default"]["NAME"] = POSTGIS_NAME
    DATABASES["default"]["USER"] = POSTGIS_USER
    DATABASES["default"]["PASSWORD"] = POSTGIS_PASS
# Set DEPLOY_SECURE to True only for LIVE deployment
if DEPLOY_SECURE:
    DEBUG = False
    TEMPLATES[0]["OPTIONS"]["debug"] = False
    ALLOWED_HOSTS = ['.kantask.io', 'localhost',]
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
else:
    DEBUG = True
    TEMPLATES[0]["OPTIONS"]["debug"] = True
    ALLOWED_HOSTS = ['*', ]
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
