# Generated by Django 4.2.5 on 2023-12-09 20:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_location', '0002_counties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='alt_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='alt_name_g',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='attributio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='epoch_tstm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='counties',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='logainm_re',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='name_ga',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='name_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='osm_timest',
            field=models.CharField(blank=True, max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='osm_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='t_ie_url',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
