# Generated by Django 4.2.5 on 2023-12-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_location', '0003_alter_counties_alt_name_alter_counties_alt_name_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
