# Generated by Django 4.2.5 on 2023-12-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_location', '0004_event_address_event_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='county',
        ),
    ]
