# Generated by Django 4.2.5 on 2023-12-18 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_location', '0005_remove_event_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='going_users',
            field=models.ManyToManyField(blank=True, related_name='going_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
