# Generated by Django 4.2.5 on 2023-11-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApiApp', '0002_alter_eds_alt_name_alter_eds_alt_name_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eds',
            name='co_osm_id',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
