# Generated by Django 4.2.5 on 2023-11-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApiApp', '0003_alter_eds_co_osm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eds',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eds',
            name='epoch_tstm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eds',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eds',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eds',
            name='osm_id',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
